In [1]:
import time

import torch

from t3_karpathy.gpt_nano_dataloader import GptNanoDataloader
from t3_karpathy.transformer_config import TransformerConfig
from t3_karpathy.transformer_runner import SentimentalRunner

torch.manual_seed(1337)

config = TransformerConfig()
#dataloader = GptNanoDataloader(config)



In [12]:
bs = 16
def get_batch():
    x = torch.tensor([[1,2,3,4,5,6,7,8,1,2,3,4,5,6,7,8,1,2,3,4,5,6,7,8,1,2,3,4,5,6,7,8] for i in range(bs)])
    y = torch.tensor([0.337 for i in range(bs)])
    x, y = x.to('cuda'), y.to('cuda')
    return x, y
get_batch()

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8,
          1, 2, 3, 4, 5, 6, 7, 8],
         [1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8,
          1, 2, 3, 4, 5, 6, 7, 8],
         [1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8,
          1, 2, 3, 4, 5, 6, 7, 8],
         [1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8,
          1, 2, 3, 4, 5, 6, 7, 8],
         [1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8,
          1, 2, 3, 4, 5, 6, 7, 8],
         [1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8,
          1, 2, 3, 4, 5, 6, 7, 8],
         [1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8,
          1, 2, 3, 4, 5, 6, 7, 8],
         [1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8,
          1, 2, 3, 4, 5, 6, 7, 8],
         [1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 

In [13]:

print("Training runner 1")
runner1 = SentimentalRunner(config)
runner1.train_iterate(5, get_batch, get_batch)
# context = torch.zeros((1, 1), dtype=torch.long, device=device)
# print(dataloader.decode(runner1.generate(context, max_new_tokens=2000)[0].tolist()))


Training runner 1
0.205569 M parameters


RuntimeError: shape '[512]' is invalid for input of size 16

In [17]:
def get_rnd_n_from_tensor(x, n):
    indices = torch.randperm(len(x))[:n]
    return x[indices]

t = torch.tensor([1,2,3,4], device='cuda')
get_rnd_n_from_tensor(t, 2)

tensor([4, 1], device='cuda:0')

In [21]:
import string

list(string.ascii_letters + string.digits) + list(string.ascii_letters + string.digits)

['a',
 'b',
 'c',
 'd',
 'e',
 'f',
 'g',
 'h',
 'i',
 'j',
 'k',
 'l',
 'm',
 'n',
 'o',
 'p',
 'q',
 'r',
 's',
 't',
 'u',
 'v',
 'w',
 'x',
 'y',
 'z',
 'A',
 'B',
 'C',
 'D',
 'E',
 'F',
 'G',
 'H',
 'I',
 'J',
 'K',
 'L',
 'M',
 'N',
 'O',
 'P',
 'Q',
 'R',
 'S',
 'T',
 'U',
 'V',
 'W',
 'X',
 'Y',
 'Z',
 '0',
 '1',
 '2',
 '3',
 '4',
 '5',
 '6',
 '7',
 '8',
 '9',
 'a',
 'b',
 'c',
 'd',
 'e',
 'f',
 'g',
 'h',
 'i',
 'j',
 'k',
 'l',
 'm',
 'n',
 'o',
 'p',
 'q',
 'r',
 's',
 't',
 'u',
 'v',
 'w',
 'x',
 'y',
 'z',
 'A',
 'B',
 'C',
 'D',
 'E',
 'F',
 'G',
 'H',
 'I',
 'J',
 'K',
 'L',
 'M',
 'N',
 'O',
 'P',
 'Q',
 'R',
 'S',
 'T',
 'U',
 'V',
 'W',
 'X',
 'Y',
 'Z',
 '0',
 '1',
 '2',
 '3',
 '4',
 '5',
 '6',
 '7',
 '8',
 '9']

In [3]:

print("Training runner 2")
runner2 = KarpathyRunner(config)
runner2.train_iterate(5, dataloader.get_train_batch, dataloader.get_val_batch)
# context = torch.zeros((1, 1), dtype=torch.long, device=device)
# print(dataloader.decode(runner2.generate(context, max_new_tokens=2000)[0].tolist()))


Training runner 2
0.209729 M parameters
step 0: train loss 4.3210, val loss 4.3205


In [8]:

print("Training runner 2")
runner3 = KarpathyRunner(config)
runner3.train_iterate(5, dataloader.get_train_batch, dataloader.get_val_batch)
# context = torch.zeros((1, 1), dtype=torch.long, device=device)
# print(dataloader.decode(runner2.generate(context, max_new_tokens=2000)[0].tolist()))


Training runner 2
0.209729 M parameters
step 0: train loss 4.3441, val loss 4.3389


In [9]:
start_time = time.time()
it = 1000
for i in range(it):
    new_weights = neural_crossover_and_mutate(runner1.get_weights(), runner2.get_weights(), 'cuda')
    runner3.set_weights(new_weights)
print((time.time() - start_time)/it)

0.023565841913223265


In [10]:
start_time = time.time()
it = 1000
for i in range(it):
    runner3.set_weights(runner1.get_weights())
print((time.time() - start_time)/it)

0.007433110237121582


In [15]:
for name, param in runner1.model.named_parameters():
    print(param)

Parameter containing:
tensor([[ 0.1822, -0.0663, -0.3642,  ...,  1.5341,  1.6093, -0.4040],
        [-0.8393,  0.6016, -0.0554,  ...,  0.3180, -0.5543, -1.4699],
        [-2.0527,  1.8296,  1.3007,  ...,  2.1353,  0.5142,  1.2172],
        ...,
        [ 1.0680,  0.1121,  1.1379,  ..., -0.1915,  0.4222, -1.8110],
        [-1.0138, -0.4618,  0.0250,  ...,  0.2831,  0.7231, -0.8062],
        [ 0.2426, -0.1155,  0.0772,  ...,  1.4492,  0.1820,  0.3048]],
       device='cuda:0', requires_grad=True)
Parameter containing:
tensor([[-1.4346, -0.2855, -2.2833,  ...,  0.5277,  1.9466,  1.1627],
        [-0.2146,  1.6670,  0.4133,  ..., -0.0269, -1.1172,  1.6298],
        [ 0.4224, -0.8771, -0.8164,  ...,  2.1739,  0.1942,  1.2059],
        ...,
        [ 0.3977, -1.1431,  1.3187,  ..., -0.8698,  0.5074,  0.8636],
        [ 1.8288, -0.6685,  0.4520,  ..., -0.7899,  0.3757, -0.2624],
        [ 0.6622, -0.8086,  2.8318,  ...,  0.0897, -0.5979, -0.7252]],
       device='cuda:0', requires_grad=True)


Parameter containing:
tensor([[ 0.0367, -0.0227, -0.0555,  ...,  0.0446, -0.0549, -0.0254],
        [ 0.0617,  0.0021, -0.0238,  ...,  0.0628, -0.0920, -0.0839],
        [-0.0974, -0.0916, -0.0503,  ...,  0.0087,  0.1105, -0.0855],
        ...,
        [-0.0495,  0.0941,  0.0926,  ..., -0.1091, -0.0600, -0.1157],
        [ 0.0737, -0.1058, -0.1102,  ..., -0.0638,  0.0561, -0.0136],
        [-0.0712,  0.0283,  0.0430,  ...,  0.0523, -0.0364,  0.0429]],
       device='cuda:0', requires_grad=True)
Parameter containing:
tensor([ 1.2795e-01, -8.9967e-02, -7.6018e-02,  1.1593e-01, -2.5266e-02,
        -3.5675e-02,  1.0380e-01,  1.0456e-01, -3.7690e-03,  7.0011e-02,
         1.1643e-01,  1.9248e-02, -7.2731e-02,  6.1754e-02,  8.1993e-03,
         2.2774e-02, -4.4465e-02, -1.0123e-02, -1.5658e-02,  3.8340e-02,
         6.2163e-03,  1.0658e-01, -1.3392e-06,  7.6502e-02, -8.5645e-02,
        -9.1426e-02, -4.7146e-02,  1.2340e-01, -2.9005e-02, -3.1789e-02,
         5.7312e-02,  1.7217e-02,  9.118

In [35]:
start_time = time.time()
it = 100
for i in range(it):
    xy1_weights = runner1.get_weights()
    xy2_weights = runner2.get_weights()
    
    new_weights = []
    for k1, _ in xy1_weights.items():
        shape = xy1_weights[k1].shape
        v1 = xy1_weights[k1].reshape(-1)
        v2 = xy2_weights[k1].reshape(-1)

        #rnd1 = torch.rand(v1.shape, device='cuda')

        #update = (v1 * rnd1 + (1 - rnd1) * v2)
        
        update = (v1 + v2)

        update = xy1_weights[k1] + xy2_weights[k1]#update.reshape(shape)
        new_weights.append((k1, update))
        
    runner3.set_weights(new_weights)
print((time.time() - start_time)/it)

0.01384002685546875


In [25]:
start_time = time.time()
it = 100
for i in range(it):    
    for _ in range(100):
        rnd1 = torch.rand(16384, device='cuda')

print((time.time() - start_time)/it)

0.0024154329299926757
