In [1]:
import torch

# create two sample vectors
inps = torch.randn([64, 161, 1])
d = torch.randn([64, 161])

In [2]:
new_inps = torch.cat((inps, d.unsqueeze(2)), dim=-1)
print(new_inps.shape)  # [64, 161, 2]

torch.Size([64, 161, 2])


In [ ]:
# bring d into the same format, and then concatenate tensors
new_inps = torch.cat((inps, d.unsqueeze(2)), dim=-1)
print(new_inps.shape)  # [64, 161, 2]`

In [91]:
def add_tensor(x_data, x):
    # define the condition to check if x exists in x_data
    condition = torch.any(torch.eq(x_data, x[:, None]), dim=2)
    # get the indices of rows that will be added to x_data
    added_indices = torch.where(~condition)[0]
    #print(added_indices)
    added_indices = added_indices.squeeze()
    # select the rows from x that will be added to x_data
    added_x = torch.index_select(x, 0, added_indices)
    # concatenate the selected rows of x with x_data
    x_data = torch.cat((x_data, added_x))
    # remove duplicate rows
    x_data = torch.unique(x_data, dim=0)
    
    return added_indices


In [92]:
x_data = torch.tensor([[1, 2, 3], [1, 2, 3],[4, 5, 6], [7, 8, 9]])
x = torch.tensor([[1, 2, 3], [1, 2, 3],[1, 2, 0],[1, 2, 5]])

add_tensor(x_data, x)

tensor([0, 0, 1, 1, 2, 2, 3, 3])

In [84]:
import torch

x_data = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

def add_tensor(x):
    global x_data
    # define the condition to check if x exists in x_data
    condition = torch.any(torch.eq(x_data, x[:, None]), dim=2)
    # get the indices of rows that will be added to x_data
    added_indices = torch.where(~condition)
    added_indices = added_indices.squeeze()
    # select the rows from x that will be added to x_data
    added_x = torch.index_select(x, 0, added_indices)
    # concatenate the selected rows of x with x_data
    x_data = torch.cat((x_data, added_x))
    # remove duplicate rows
    x_data = torch.unique(x_data, dim=0)

x = torch.tensor([[1, 2, 3], [1, 2, 3],[1, 2, 3],[1, 2, 5]])
add_tensor(x)
print(x_data)

AttributeError: 'tuple' object has no attribute 'squeeze'

In [51]:

x_data = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
y_data = torch.tensor([[4, 5, 6], [10, 11, 12]])


In [78]:

x = torch.tensor([[1, 2, 3], [1, 2, 3],[1, 2, 3],[1, 2, 3]])
#x = torch.empty(1,3)

print(x[None])

condition = torch.any(torch.eq(x_data, x), dim=2)

condition

tensor([[[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]]])


RuntimeError: The size of tensor a (3) must match the size of tensor b (4) at non-singleton dimension 0

In [ ]:
import torch

x_data = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
y_data = torch.tensor([[4, 5, 6], [10, 11, 12]])

def add_tensor(x, y):
    # define the condition to check if x exists in x_data
    condition = torch.any(torch.eq(x_data, x[None]), dim=1)
    #get the indices of rows that will be added to x_data
    added_indices = torch.where(~condition)
    added_indices = added_indices.squeeze()

    # check if x exists in x_data
    if not condition.any():
        global x_data, y_data
        # add x to x_data
        x_data = torch.cat((x_data, x[None]))
        # add y to y_data
        selected_y = torch.index_select(y, 0, added_indices)
        y_data = torch.cat((y_data, selected_y))
    return added_indices

x = torch.tensor([10, 11, 12])
y = torch.tensor([[13, 14, 15], [16, 17, 18], [19, 20, 21]])
print(add_tensor(x, y)) # tensor([[3]])

x = torch.tensor([1, 2, 3])
y = torch.tensor([[13, 14, 15], [16, 17, 18], [19, 20, 21]])
print(add_tensor(x, y)) # tensor([], size=(0, 1))
In this example, torch.index_select(y, 0, added_indices) selects the rows of y that have the corresponding added_indices along the 0th axis.

Finally, torch.cat((y_data, selected_y)) concatenates the selected rows of y with y_data along the 0th axis.

Please note that, as x_data and y_data are global variable, if you want to update them inside the function, you need to use global x_data, y_data at the start of the function. Also, if the added_indices is empty, torch.index_select(y, 0, added_indices) will return an empty tensor, and torch.cat((y_data, selected_y)) will not add any row to y_data.




How do i 


In [38]:
d

tensor([[ 1.4467, -0.4909],
        [-0.1533,  0.2013],
        [ 1.3653, -1.2441],
        [ 1.3534, -0.1226]])

In [44]:
d.unsqueeze(1)

tensor([[[ 1.4467, -0.4909]],

        [[-0.1533,  0.2013]],

        [[ 1.3653, -1.2441]],

        [[ 1.3534, -0.1226]]])

In [49]:
# create two sample vectors
inps = torch.randn([64, 161, 1])
d = torch.randn([64, 161])

def add_tensor(to, x):
    return torch.cat((to, x.unsqueeze(2)), dim=-1)

inps = add_tensor(inps, d)
inps = add_tensor(inps, d)
inps = add_tensor(inps, d)
inps.shape

torch.Size([64, 161, 4])

In [45]:
tensor1 = torch.tensor([1, 2, 3])
tensor2 = torch.tensor([4])

tensor2 = torch.unsqueeze(tensor2, dim=0)
result = torch.cat((tensor1, tensor2), dim=0)

result

RuntimeError: Tensors must have same number of dimensions: got 1 and 2

In [50]:
torch.tensor()

tensor([1, 2])